token = "token"
prefix = "!"
user_agent = "user_agent"
real_user_agent = "real_user_agent"
internal_api_url = "internal_api_url"
cdn_url = "cdn_url"
main_guild_id = 1
dev_guild_id = 1

[secrets]
api = "api"
catbox = "catbox"
github = "github"
cloudflare = "cloudflare"
openai = "openai"
deepl = "deepl"
